// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYVM4Dt-NtWWg3bkKuFDXPuiDBxtbki5M',
    appId: '1:397633807448:android:31e5c13ef76a264669562d',
    messagingSenderId: '397633807448',
    projectId: 'pb-term-project',
    storageBucket: 'pb-term-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc9zh5nSzOXjqr6NY92jjbR-Cd2QuxMnw',
    appId: '1:397633807448:ios:f92620de8ae94b2869562d',
    messagingSenderId: '397633807448',
    projectId: 'pb-term-project',
    storageBucket: 'pb-term-project.firebasestorage.app',
    iosClientId: '397633807448-a8hlip1itofk6np55h9el6encvgpoaja.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvFPfn9Qu90NZtk4QgSSe0R90dmkLStl0',
    appId: '1:397633807448:web:180c2547b16cebba69562d',
    messagingSenderId: '397633807448',
    projectId: 'pb-term-project',
    authDomain: 'pb-term-project.firebaseapp.com',
    storageBucket: 'pb-term-project.firebasestorage.app',
    measurementId: 'G-MHSE4C72G4',
  );

}